🚧 - Implementar Interactor do módulo Confirmation
devpass-tech/challenge-viper-finance pull request #16
Opened 2022-02-03 20:38 UTC by leschlogl

### Implementar Interactor do módulo Confirmation
 
Implementação do Interactor gerando um mock com a tela de confirmação recebendo um estado de loading.
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [X] Não adiciona código duplicado
- [X] Não contém código comentado
- [X] Não contém código WIP
 
### Evidências da feature:
| iPhone SE | iPhone 12 Max |
| ------ | ------ |
|  ![ezgif-2-a61bdd306a](https://user-images.githubusercontent.com/6379664/152424739-89c448a1-bf2f-45da-a693-a25c9512ef70.gif) | ![ezgif-2-41fad35279](https://user-images.githubusercontent.com/6379664/152424778-1821444c-34be-4a81-9926-4df4c59e1fdd.gif) |

2022-02-03 21:08 UTC, jjfernandes87 requested changes

2022-02-03 21:08 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationView.swift
> +struct Confirmation {
Ideal aqui seria você criar um arquivo ConfirmationEntity e lá dentro você colocar a struct e o enum

2022-02-03 21:08 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationView.swift
> +    var state: ConfirmationViewState = .loading {
Aqui a variável não poderia ser private(set), dessa forma vc garante uma integridade maior dela, ninguém fora do próprio escopo poderia alterar

2022-02-03 21:08 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationView.swift
> +    let image: UIImage?
Ideal seria retornar String, pensando que isso é um modelo de negocio

2022-02-03 21:08 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationInteractor.swift
> +import UIKit
Remover o UIKit, já que a struct do Confirmation não terá UIImage

2022-02-03 21:08 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationInteractor.swift
> +            let confirmation = Confirmation(success: true, image: UIImage(named: "checkmark.circle.fill"), message: "Your transfer was successful")
Com a sua alteração no modelo o UIImage deixa de ser obrigatório e retornaria apenas "checkmark.circle.fill"

2022-02-07 14:38 UTC, leschlogl commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationView.swift
> +    var state: ConfirmationViewState = .loading {
Aqui na View se eu mudar pra private(set), eu não consigo mudar da ViewController o estado dela. Deveria eu deixar essa variável privada e usar um método interno para realizar a mudança de estado da view?

2022-02-07 21:15 UTC, jjfernandes87 approved these changes

2022-02-07 21:15 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationView.swift
> +    var state: ConfirmationViewState = .loading {
Exato, o melhor cenário é você ter um método que altere esse estado. 

ex: no loaded(ConfirmationEntity) você pode alterar esse estado,

2022-02-07 21:15 UTC, merged