🚧 - Implementar estrutura do módulo Transfers
devpass-tech/challenge-viper-finance pull request #19
Opened 2022-02-04 02:05 UTC by AlexandreBCardoso

### Descrição simples da nova feature
* Criação da estrutura do VIPER para o módulo Transfers
* [Task Notion](https://www.notion.so/devpass/9c9ee019fe09445a959ca7a31f6192a4?v=19d645691f8d4ad7835a7c7d6d73ac0c&p=b2263cd7d3a54d8e8d0957f796e54144)
 
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [] Não contém código WIP
 
### Evidências da feature:
| iPhone SE | iPhone 12 Max |
| ------ | ------ |
| print  | print |

2022-02-04 17:24 UTC, jjfernandes87 requested changes

2022-02-04 17:24 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersViewController.swift
> +		presenter.router.navigateToContactList()
Aqui o ideal seria chamar a presenter, nossa ViewController não deveria conhecer que existe uma variável Router. 

Por isso que o ideal é que as variáveis de uma classe sejam private, evitando esse tipo de acesso direto

2022-02-04 17:24 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersViewController.swift
> +		presenter.router.navigateToConfirmation()
O mesmo vale para esse método ;)

2022-02-07 21:18 UTC, jjfernandes87 requested changes

2022-02-07 21:18 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Components/TabBarController.swift
> +		  let transfersViewController = TransfersRouter.createModule()
Não sei se aqui ficou errado a indentação

2022-02-07 21:18 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersView.swift
> +	 @available(*, unavailable)
Aqui também ficou certa a indentação?

2022-02-07 21:36 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Components/TabBarController.swift
> +		  let transfersViewController = TransfersRouter.createModule()
Acredito que seja a indentação do meu Xcode que esteja diferente do padrão.

2022-02-08 21:19 UTC, jjfernandes87 requested changes

2022-02-08 21:19 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersRouter.swift
> +		self.viewController?.show(navController, sender: self)
O ContactListRouter.createModule() retorna um UINavigationController ou UIViewController?

2022-02-08 21:19 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersRouter.swift
> +		self.viewController?.show(navController, sender: self)
O ConfirmationRouter.createModule() retorna um UINavigationController ou UIViewController?

2022-02-08 21:19 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersViewController.swift
> +	lazy var transferView: TransfersView = {
O que você acha de deixar private?

2022-02-08 21:33 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersViewController.swift
> +	lazy var transferView: TransfersView = {
Done

2022-02-08 21:37 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersViewController.swift
> +		presenter.router.navigateToContactList()
Done

2022-02-08 21:37 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersViewController.swift
> +		presenter.router.navigateToConfirmation()
Done

2022-02-08 22:13 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Components/TabBarController.swift
> +		  let transfersViewController = TransfersRouter.createModule()
Done

2022-02-08 22:13 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersView.swift
> +	 @available(*, unavailable)
Done

2022-02-08 22:14 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersRouter.swift
> +		self.viewController?.show(navController, sender: self)
Está retornando UINavigationController. Já troquei para retornar UIViewController.

2022-02-08 22:14 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Transfers/TransfersRouter.swift
> +		self.viewController?.show(navController, sender: self)
Está retornando UINavigationController. Já troquei para retornar UIViewController.

2022-02-08 23:00 UTC, jjfernandes87 approved these changes

2022-02-08 23:00 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/ContactList/ContactListViewController.swift
> +		title = "Contact list"
Isso não poderia ficar no próprio createModule?

2022-02-09 13:31 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/ContactList/ContactListViewController.swift
> +		title = "Contact list"
Não é possível ficar na Router, fiz um testes e só consegui dessa forma.

2022-02-09 21:46 UTC, jjfernandes87 approved these changes

2022-02-09 21:47 UTC, merged