✨ - Implementar método do Service para UserProfile
devpass-tech/challenge-viper-finance pull request #22
Opened 2022-02-06 21:07 UTC by AlexandreBCardoso

### Descrição simples da nova feature
* Implementação de Entity UserProfile
* Implementação de Service UserProfile 
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:
N/A

2022-02-08 21:45 UTC, jjfernandes87 requested changes

2022-02-08 21:45 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entities/UserEntity.swift
> +   let phone: String
Aqui também seria a questão de indentação ;)

2022-02-08 21:45 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entities/AccountEntity.swift
> +struct AccountEntity: Decodable {
Essa struct ideal que fosse movida para dentro do modulo de Account que ja que ele faz parte da estrutura do VIPER ;)

2022-02-08 21:45 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/UserProfileService.swift
> +	func fetchUser(urlString: String, completion: @escaping (Result<UserEntity, FinanceError>) -> Void) {
Excelente o código, mas pensando que esses dados estão locais, ideal seria ter um tratamento para pegar do bundle local ou ate mesmo remover o URLSession e fazer algo mais simples, o que acha?

2022-02-08 22:28 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entities/UserEntity.swift
> +   let phone: String
Done

2022-02-08 22:31 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entities/AccountEntity.swift
> +struct AccountEntity: Decodable {
Coloquei a entity User e Account dentro do modulo de UserProfile.

2022-02-08 22:33 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/UserProfileService.swift
> +	func fetchUser(urlString: String, completion: @escaping (Result<UserEntity, FinanceError>) -> Void) {
Sim, eu pensei em usar o pegar do bundle local, mas achei mais interessante utilizar o URLSession para "simular" o dia a dia com chamada de API.

2022-02-08 23:05 UTC, jjfernandes87 requested changes

2022-02-08 23:05 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/UserProfileService.swift
> +	func fetchUser(urlString: String, completion: @escaping (Result<UserEntity, FinanceError>) -> Void) {
O que vc acha alterar fetchUser para request ... ja que fetchUser passa uma impressão que são apenas dados de usuário

2022-02-09 11:28 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/UserProfileService.swift
> +	func fetchUser(urlString: String, completion: @escaping (Result<UserEntity, FinanceError>) -> Void) {
Done.

2022-02-10 21:57 UTC, jjfernandes87 approved these changes

2022-02-10 21:57 UTC, merged