✨ - Implementar Router do módulo Home
devpass-tech/challenge-viper-finance pull request #24
Opened 2022-02-07 22:48 UTC by AlexandreBCardoso

### Descrição simples da nova feature
* Implementado a camada de Router da Home
* Atualizado a instancia da HomeViewController para chamada do método que instancia a Home na Router
 
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:
| iPhone SE | iPhone 12 Max |
| ------ | ------ |
| <img width="309" alt="iPhone-SE" src="https://user-images.githubusercontent.com/48521614/152885073-818a0a34-f787-4823-966c-83db0894d628.png">  | <img width="312" alt="iPhone-12" src="https://user-images.githubusercontent.com/48521614/152885178-2ddef7e2-e6e1-4bf6-ab5f-f7272cae93cf.png"> |

2022-02-08 21:23 UTC, jjfernandes87 requested changes

2022-02-08 21:23 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeProtocols.swift
> +	func navigationToUserProfile()
Acho que esse método será implementado apenas na outras task do Board. Para não ficar a implementação vazia, o que você acha de colocar ele apenas depois?

2022-02-08 21:23 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeProtocols.swift
> +	func navigateToActivityDetails()
O mesmo para esse metodo ;)

2022-02-08 21:23 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeRouter.swift
> +	func navigationToUserProfile() { }
Sem o protocolo, essa função vazia seria removida

2022-02-08 21:23 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeRouter.swift
> +	func navigateToActivityDetails() { }
O mesmo para esse metodo ;)

2022-02-10 01:42 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeProtocols.swift
> +	func navigationToUserProfile()
Done

2022-02-10 01:42 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeProtocols.swift
> +	func navigateToActivityDetails()
Done

2022-02-10 01:42 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeRouter.swift
> +	func navigationToUserProfile() { }
Done

2022-02-10 01:42 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Home/HomeRouter.swift
> +	func navigateToActivityDetails() { }
Done

2022-05-25 20:09 UTC, jjfernandes87 approved these changes

2022-05-25 20:09 UTC, merged