Implementado a camada Router do módulo ActivityDetails
devpass-tech/challenge-viper-finance pull request #26
Opened 2022-02-08 01:40 UTC by sarafelix25

### Descrição simples da nova feature
 - Ajuste na estrutura, mantendo padrão da equipe
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:
|  |
| ------ | 
| <img width="1440" alt="Captura de Tela 2022-02-07 às 22 38 44" src="https://user-images.githubusercontent.com/70541669/152901636-55295741-e0e2-4cd0-b565-e71a0e400c73.png">  |

2022-02-08 21:27 UTC, jjfernandes87 requested changes

2022-02-08 21:27 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/ActivityDetails/ActivityDetailsPresenter.swift
>      var interactor: ActivityDetailsInteractorProtocol?
Sugestão
```
var interactor: ActivityDetailsInteractorProtocol
```

Como você esta passando pelo init, sempre teremos uma instancia do interactor

2022-02-08 21:27 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/ActivityDetails/ActivityDetailsPresenter.swift
>      var router: ActivityDetailsRouterProtocol?
O mesmo vale para o router ;)

2022-02-10 21:26 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp.xcodeproj/project.pbxproj
> +				ARCHS = x86_64;
Acho que veio essa mudança por conta do M1 neh

2022-02-15 00:46 UTC, sarafelix25 commented on solutions/devsprint-julio-fernandes-1/FinanceApp.xcodeproj/project.pbxproj
> +				ARCHS = x86_64;
Sim, qdo usa m1 se tem podfile, tem que mudar pra essa arquitetura tbm

2022-02-17 10:57 UTC, jjfernandes87 approved these changes

2022-05-25 20:09 UTC, merged