✨ - Implementar método do Service para Home
devpass-tech/challenge-viper-finance pull request #28
Opened 2022-02-08 14:55 UTC by AlexandreBCardoso

### Descrição simples da nova feature
 * Adicionado os entity para a Home
 * Adicionado a camada Service para chamada do endpoint da Home
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:
N/A

2022-02-08 21:45 UTC, jjfernandes87 requested changes

2022-02-08 21:45 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entity/ActivityEntity.swift
> +struct ActivityEntity: Decodable {
Vamos mover essa Entity para dentro do Module ActivityDetails

2022-02-08 21:45 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entity/HomeEntity.swift
> +struct HomeEntity: Decodable {
Vamos mover essa Entity para dentro do Module Home

2022-02-08 21:45 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/HomeService.swift
> +	func load(urlString: String, completion: @escaping (Result<HomeEntity, NSError>) -> Void)
Sugestão: 
func request(urlString: String, completion: @escaping (Result<HomeEntity, ServiceError >) -> Void)

enum ServiceError: NSError {}

Dessa forma conseguimos tratar melhor os erros criando um enum que extende do NSError

2022-02-08 22:46 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entity/ActivityEntity.swift
> +struct ActivityEntity: Decodable {
Done

2022-02-08 22:46 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/Entity/HomeEntity.swift
> +struct HomeEntity: Decodable {
Done

2022-02-08 22:47 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/HomeService.swift
> +	func load(urlString: String, completion: @escaping (Result<HomeEntity, NSError>) -> Void)
Done

2022-02-09 21:35 UTC, jjfernandes87 requested changes

2022-02-09 21:35 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/HomeService.swift
> +struct HomeAPI: HomeService {
Vamos remover essa HomeService e centralizar a FinanceService como nosso provier de serviço. O Lucas esta pegando essa demanda, acho que nesse caso podemos apenas usar o Entity criado

2022-02-10 01:46 UTC, AlexandreBCardoso commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Service/HomeService.swift
> +struct HomeAPI: HomeService {
Done

2022-02-10 21:59 UTC, jjfernandes87 approved these changes

2022-02-10 22:00 UTC, jjfernandes87 approved these changes

2022-02-12 12:51 UTC, jjfernandes87 approved these changes

2022-02-12 12:51 UTC, merged