✨- Implementar Presenter do módulo Transfers
devpass-tech/challenge-viper-finance pull request #36
Opened 2022-02-11 18:26 UTC by leschlogl

### Implementar Presenter do módulo Transfers
- Adicionado logica do presenter de transfer
- Alterado a lógica de apresentaçao de sucesso/erro na Confirmation
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [X] Não adiciona código duplicado
- [X] Não contém código comentado
- [X] Não contém código WIP

2022-02-11 21:35 UTC, jjfernandes87 requested changes

2022-02-11 21:35 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationEntity.swift
> +    let color: UIColor
Como modelo de negocio ele não carregaria UIKit, podemos pensar ou String passando um hexadecimal ou no nosso caso podemos usar o state ou ate o sucess

2022-02-11 21:37 UTC, leschlogl commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationEntity.swift
> +    let color: UIColor
done :)

2022-02-12 12:52 UTC, jjfernandes87 approved these changes

2022-02-12 12:53 UTC, merged