✨ - Implementar estrutura do módulo Confirmation
devpass-tech/challenge-viper-finance pull request #6
Opened 2022-02-01 22:12 UTC by leschlogl

### Estrutura módulo Confirmation
 
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [X] Não adiciona código duplicado
- [X] Não contém código comentado
- [X] Não contém código WIP
 
### Evidências da feature:
| iPhone SE | iPhone 12 Max |
| ------ | ------ |
|![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-02-01 at 19 11 05](https://user-images.githubusercontent.com/6379664/152060099-9bdc490c-7200-4eda-90b5-7dd65df5dfea.png)  | ![Simulator Screen Shot - iPhone 12 Pro Max - 2022-02-01 at 19 09 51](https://user-images.githubusercontent.com/6379664/152060147-b37e1e88-bbb5-4488-8fa7-da53fa1a6129.png) |

2022-02-01 23:12 UTC, jjfernandes87 requested changes

2022-02-01 23:12 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationRouter.swift
> +class ConfirmationRouter: ConfirmationRouterProtocol {
O que você acha de adicionar o final no começo da classe? 

Você pode ver mais a respeito disso nesse link: [https://developer.apple.com/swift/blog/?id=27](https://developer.apple.com/swift/blog/?id=27)
 
_Use final quando souber que uma declaração não precisa ser substituída.
A palavra-chave final é uma restrição em uma classe, método ou propriedade que indica que a declaração não pode ser substituída._

2022-02-01 23:19 UTC, leschlogl commented on solutions/devsprint-julio-fernandes-1/FinanceApp/Modules/Confirmation/ConfirmationRouter.swift
> +class ConfirmationRouter: ConfirmationRouterProtocol {
Ajustado! Acabou faltando de colocar no Router. Obrigado!

2022-02-02 00:03 UTC, jjfernandes87 approved these changes

2022-02-02 00:03 UTC, merged